//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4200
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MxBots {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ClassSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ClassSettings defaultInstance = ((ClassSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ClassSettings())));
        
        public static ClassSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList ClassesDistances {
            get {
                return ((global::System.Collections.ArrayList)(this["ClassesDistances"]));
            }
            set {
                this["ClassesDistances"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<BotConfig xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <FollowDistance>0</FollowDistance>
  <minDistance>0</minDistance>
  <maxDistance>0</maxDistance>
</BotConfig>")]
        public global::MxBots.BotConfig btc {
            get {
                return ((global::MxBots.BotConfig)(this["btc"]));
            }
            set {
                this["btc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList DistanceDuMain {
            get {
                return ((global::System.Collections.ArrayList)(this["DistanceDuMain"]));
            }
            set {
                this["DistanceDuMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList MinTargetDistance {
            get {
                return ((global::System.Collections.ArrayList)(this["MinTargetDistance"]));
            }
            set {
                this["MinTargetDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList MaxTargetDistance {
            get {
                return ((global::System.Collections.ArrayList)(this["MaxTargetDistance"]));
            }
            set {
                this["MaxTargetDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MageWaitTankPull {
            get {
                return ((bool)(this["MageWaitTankPull"]));
            }
            set {
                this["MageWaitTankPull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int MageTimeToWaitTankAgro {
            get {
                return ((int)(this["MageTimeToWaitTankAgro"]));
            }
            set {
                this["MageTimeToWaitTankAgro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList PreCombatTick {
            get {
                return ((global::System.Collections.ArrayList)(this["PreCombatTick"]));
            }
            set {
                this["PreCombatTick"] = value;
            }
        }
    }
}
